---
- hosts: video-compressor
  vars:
    docker_image: stepic/video-compressor
    docker_tag: latest
  become: yes
  tasks:
  - name: start video-compressor container
    docker:
      name: video-compressor
      image: "{{ docker_image }}:{{ docker_tag }}"
      pull: always
      state: reloaded
      restart_policy: always
      env:
        IS_DOCKER: "true"
      ports:
        - "10080:80"
